name: Docker Image CI

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/678591755363/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-830@cloudlabs-387310.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Echo GCP Environment Variable'
      run: echo ${GOOGLE_APPLICATION_CREDENTIALS}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS} --tag cloudlabs-app:$(date +%s)